title: Team Merlin's Magical Bird-like Blog
description: A place for our developers to report weekly progress
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: neon
